### ISSUE TITLE
Display button only in results pages

### ISSUE THREAD

**Issue by vogloblinsky** [YoamFarges/LaBonneCarte#11]
Thanks for this great job, it helps me a lot for a recent research with map use-case.

I notice that the activation button of the map is displayed everywhere : homepage, messages, etc

I can submit a PR if you want, to display it only on :
- https://www.leboncoin.fr/recherche

**Comment by YoamFarges** [comment]
Hello, thanks for the proposition!

The problem is that Leboncoin's app does not trigger a full page change when going from page to page. Seems that their system is simply triggering a History.pushState or something like that.
That means it's not as simple as changing the _manifest.json's content_scripts.matches_ parameter. 

The change probably requires the 'tabs' permission, and adding a listener on the background like
```
chrome.tabs.onUpdated.addListener(
  function(tabId, changeInfo, tab) {
    // read changeInfo data and do something with it
    // like send the new url to contentscripts.js
    if (changeInfo.url) {
      chrome.tabs.sendMessage( tabId, {
        message: 'hello!',
        url: changeInfo.url
      })
    }
  }
);
```


I attempted to do something like that at one point, but decided against it due to the fact that:
- It works now
- It is one less permission to ask for the end user


So if you have a better idea / implementation, or if you just want to experiment feel free to do so but I would not say it's worth it.

**Comment by vogloblinsky** [comment]
Yes, the callback onpopstate is only available on window for back and next button.
