### ISSUE TITLE
How to use without Chrome store?

### ISSUE THREAD

**Issue by VictorLamoine** [YoamFarges/LaBonneCarte#5]
It seems that the extension was removed from the Chrome store.
I'm using Kubuntu 18.04

- I have cloned the git repository
- I have enabled developer mode in Chrome (`68.0.3440.84-1`)
- I have added the extension using the "Chargez l'extension non empaquetée" button

![screenshot_20180805_153252](https://user-images.githubusercontent.com/5566160/43686364-d9abd24c-98c4-11e8-9a44-852272f38ce4.png)

No map is displayed when I do a search on leboncoin.
Any idea what may be wrong?

**Comment by YoamFarges** [comment]
Hello Victor, it seems that you did everything right, but unfortunately the project is not functional anymore due to Google Maps policy changes + leboncoin architecture change. I was working on it but due to time constraints it's on hold at the moment : that's why it was removed from the chrome store.

I apologise sincerely about that, but I will make sure that I ping you when I will make the project functional again (late August I think).

PS: if you want to help, you can too, feel free to fork the project 😀

**Comment by VictorLamoine** [comment]
I have zero knowledge in javascript so I can't help but thank you for the update!
