### ISSUE TITLE
Question: How address are filtered ?

### ISSUE THREAD

**Issue by storm1er** [YoamFarges/LaBonneCarte#6]
Hi,

Awesome jobs, almost perfect <3 

But I don't know if this it's a bug or not: When loading a search page, all results aren't displayed.
Therefore all results have at least a city. So why don't they appear on the map?

Thanks.

**Comment by YoamFarges** [comment]
Hello, thanks for the message.

So, yeah, sorry the project is a little bit outdated.

Leboncoin did start using React and obfuscation methods, which leads to incorrect HTML parsing on the extension's side. 
Also, React's way of displaying the pages asynchronously makes it painful for the extension to know when to display the map, and almost impossible to retrieve the thumbnails of the items without scrolling to the whole page.

So there is still no ETA because to be honest I was quite discouraged by their methods, but if I were to change something I would :
- Remove the map displaying automatically on top of the page
- Make the map only appear in a popup when you click manually click on the top-right extension icon
- Stop trying to figure out when a page refresh its information, and just parse the HTML snapshot of whenever the map is loaded.

Even with this oversimplification there would be some stuff that would not work properly, but at least it somehow work.

So, I'll see what I can do about all of this but to be fair, don't expect something anytime soon. Feel free to contribute to the project though.

Best,
Yoam

**Comment by YoamFarges** [comment]
PS: to answer your initial question, you can look at /foreground/parser/webpageparser.js . All of the parsing logic would be here.
